package com.mrd.drools.business.mapper;

import com.github.pagehelper.Page;
import com.mrd.drools.business.entity.TdRule;
import com.mrd.drools.business.entity.TdRuleWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TdRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int insert(TdRuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int insertSelective(TdRuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    TdRuleWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int updateByPrimaryKeySelective(TdRuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(TdRuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    int updateByPrimaryKey(TdRule record);

    List<TdRuleWithBLOBs> selectTdRuleList(@Param("flagDelete") Integer flagDelete);

    Page<TdRuleWithBLOBs> selectList(TdRuleWithBLOBs tdRule);

}