package com.mrd.drools.business.mapper;

import com.github.pagehelper.Page;
import com.mrd.drools.business.entity.TdRuleColumn;
import org.springframework.stereotype.Repository;

@Repository
public interface TdRuleColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    int insert(TdRuleColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    int insertSelective(TdRuleColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    TdRuleColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    int updateByPrimaryKeySelective(TdRuleColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    int updateByPrimaryKey(TdRuleColumn record);

    Page<TdRuleColumn> selectList(TdRuleColumn tdRuleColumn);

}