package com.mrd.drools.business.entity;

import java.io.Serializable;

public class TdRuleWithBLOBs extends TdRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.content
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.rule
     *
     * @return the value of td_rule.rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.rule
     *
     * @param rule the value for td_rule.rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.content
     *
     * @return the value of td_rule.content
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.content
     *
     * @param content the value for td_rule.content
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TdRuleWithBLOBs other = (TdRuleWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()))
            && (this.getRule() == null ? other.getRule() == null : this.getRule().equals(other.getRule()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        result = prime * result + ((getRule() == null) ? 0 : getRule().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}