package com.mrd.drools.business.entity;

import java.io.Serializable;
import java.util.Date;

public class TdRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.id
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.name
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.code
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.create_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.modify_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule.flag_delete
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.id
     *
     * @return the value of td_rule.id
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.id
     *
     * @param id the value for td_rule.id
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.name
     *
     * @return the value of td_rule.name
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.name
     *
     * @param name the value for td_rule.name
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.code
     *
     * @return the value of td_rule.code
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.code
     *
     * @param code the value for td_rule.code
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.create_time
     *
     * @return the value of td_rule.create_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.create_time
     *
     * @param createTime the value for td_rule.create_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.modify_time
     *
     * @return the value of td_rule.modify_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.modify_time
     *
     * @param modifyTime the value for td_rule.modify_time
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule.flag_delete
     *
     * @return the value of td_rule.flag_delete
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule.flag_delete
     *
     * @param flagDelete the value for td_rule.flag_delete
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TdRule other = (TdRule) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
                && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule
     *
     * @mbggenerated Wed Dec 06 15:48:09 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}