package com.mrd.drools.business.entity;

import java.io.Serializable;
import java.util.Date;

public class TdRuleColumn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.id
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.name
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.data
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.type
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.create_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.modify_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_rule_column.flag_delete
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private Integer flagDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.id
     *
     * @return the value of td_rule_column.id
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.id
     *
     * @param id the value for td_rule_column.id
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.name
     *
     * @return the value of td_rule_column.name
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.name
     *
     * @param name the value for td_rule_column.name
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.data
     *
     * @return the value of td_rule_column.data
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.data
     *
     * @param data the value for td_rule_column.data
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.type
     *
     * @return the value of td_rule_column.type
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.type
     *
     * @param type the value for td_rule_column.type
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.create_time
     *
     * @return the value of td_rule_column.create_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.create_time
     *
     * @param createTime the value for td_rule_column.create_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.modify_time
     *
     * @return the value of td_rule_column.modify_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.modify_time
     *
     * @param modifyTime the value for td_rule_column.modify_time
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_rule_column.flag_delete
     *
     * @return the value of td_rule_column.flag_delete
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public Integer getFlagDelete() {
        return flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_rule_column.flag_delete
     *
     * @param flagDelete the value for td_rule_column.flag_delete
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    public void setFlagDelete(Integer flagDelete) {
        this.flagDelete = flagDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TdRuleColumn other = (TdRuleColumn) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getFlagDelete() == null ? other.getFlagDelete() == null : this.getFlagDelete().equals(other.getFlagDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_rule_column
     *
     * @mbggenerated Tue Dec 05 16:50:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getFlagDelete() == null) ? 0 : getFlagDelete().hashCode());
        return result;
    }
}